// SPDX-License-Identifier: GPL-3.0-or-later
import { UIState, Page } from "../globals.slint";
import { DiskListPage } from "../pages/disk-list.slint";
import { PathManagementPage } from "../pages/path-management.slint";
import { ProfileSelectionView } from "../pages/profile-menu.slint";
import { PathManagementBridge } from "bridges.slint";

export component Stack inherits Rectangle {
    horizontal-stretch: 1;
    vertical-stretch: 1;
    background: transparent;

    if UIState.current-page == Page.DiskList : DiskListPage {
        width: 100%;
        height: 100%;
        analyze-disks => {
            UIState.current_page = Page.PathManagement;
            PathManagementBridge.get-start-paths();
        }
    }

    if UIState.current-page == Page.PathManagement : PathManagementPage {
        width: 100%;
        height: 100%;
        start-path-analysis => {
            UIState.current-page = Page.ProfileSelection;
        }
    }

    if current-page == Page.ProfileSelection : ProfileSelectionView {
        start-profile-analysis => {
            current-page = Page.DiskAnalysis;
            start-analysis();
        }
    }

    /*if current-page == Page.DiskAnalysis : DiskAnalysisPage {}

    if current-page == Page.AnalysisResult : AnalysisResultPage {}*/
}