// SPDX-License-Identifier: GPL-3.0-or-later
import { UIState, Page } from "../globals.slint";
import { DiskListPage } from "../pages/disk-list.slint";
import { PathManagementPage } from "../pages/path-management.slint";
import { ProfileListPage } from "../pages/profile-list.slint";
import { PathManagementBridge, AnalysisResultBridge } from "bridges.slint";
import { AnalysisResultPage } from "../pages/analysis-result.slint";

export component Stack inherits Rectangle {
    horizontal-stretch: 1;
    vertical-stretch: 1;
    background: transparent;

    if UIState.current-page == Page.DiskList : DiskListPage {
        width: 100%;
        height: 100%;
        analyze-disks => {
            UIState.current_page = Page.PathManagement;
            PathManagementBridge.get-start-paths();
        }
    }

    if UIState.current-page == Page.PathManagement : PathManagementPage {
        width: 100%;
        height: 100%;
        start-path-analysis => {
            UIState.current-page = Page.ProfileSelection;
        }
    }

    if UIState.current-page == Page.ProfileSelection : ProfileListPage {
        width: 100%;
        height: 100%;
        start-profile-analysis => {
            UIState.current-page = Page.AnalysisResult;
            AnalysisResultBridge.initialize();
        }
    }

    if UIState.current-page == Page.AnalysisResult : AnalysisResultPage {
        width: 100%;
        height: 100%;
    }
}