// SPDX-License-Identifier: GPL-3.0-or-later
import { DiskListView, DiskAnalysisView, PathManagementView, ProfileSelectionView } from "index.slint";
import { WindowSettings } from "global.slint";
import { VerticalBox } from "std-widgets.slint";

export { DiskListAdapter, PathListAdapter, ProfileListAdapter } from "components/index.slint";

enum Page {
    DiskList,
    PathManagement,
    DiskAnalysis,
    ProfileSelection,
}

export component App inherits Window {
    min-width: WindowSettings.min-window-width;
    min-height: WindowSettings.min-window-height;
    title: WindowSettings.title;
    icon: WindowSettings.icon;
    

    property <Page> current-page: DiskList;

    callback load-paths;
    
    VerticalLayout {
        padding: 20px;
        spacing: 16px;

        if current-page == Page.DiskList : DiskListView {
            analyze-disks => {
                current_page = Page.PathManagement;
                load-paths();
            }
        }
    
        if current-page == Page.DiskAnalysis : DiskAnalysisView {
            disk-analyzed => {
                current-page = Page.ProfileSelection;
            }
        }

        if current-page == Page.PathManagement : PathManagementView {
            start-analysis => {
                current-page = Page.ProfileSelection;
            }
        }

        if current-page == Page.ProfileSelection : ProfileSelectionView {
            
        }
    }
}
