// SPDX-License-Identifier: GPL-3.0-or-later
import { DiskListView } from "index.slint";
import { WindowSettings } from "global.slint";
import { VerticalBox } from "std-widgets.slint";

export { DiskListAdapter } from "components/index.slint";

export component App inherits Window {
    min-width: WindowSettings.min-window-width;
    min-height: WindowSettings.min-window-height;
    title: WindowSettings.title;
    icon: WindowSettings.icon;


    VerticalBox {
        padding: 16px;

        DiskListView {
            width: 100%;
        }
    }
}
