// SPDX-License-Identifier: GPL-3.0-or-later
import { Themes } from "./modules/surrealism-ui/use/index.slint";

//! global styles
export global ROOT_GLOBAL {
    in-out property <length> min-window-height: 600px;
    in-out property <length> min-window-width: 800px;
    in-out property <length> font-size: 16px;
    in-out property <length> padding: 0px;
    in-out property <string> title: "Foruster";
    in-out property <image> icon: @image-url("assets/surrealism.png");

    in-out property <Themes> theme: Themes.Dark;
}
