// SPDX-License-Identifier: GPL-3.0-or-later
import { Themes } from "./modules/surrealism-ui/use/index.slint";
//import { Disk } from "./components/index.slint";

export global ROOT_GLOBAL {
    in-out property <length> min-window-height: 600px;
    in-out property <length> min-window-width: 800px;
    in-out property <length> font-size: 16px;
    in-out property <length> padding: 0px;
    in-out property <string> title: "Foruster";
    in-out property <image> icon: @image-url("assets/surrealism.png");

    in-out property <Themes> theme: Themes.Dark;
}

export global GLOBAL_DATA {
    //in-out property <[Disk]> disks_data;

    // Error Handling
    in-out property <bool> error_occurred: false;
    in-out property <string> error_message: "";
    public function show_error(message: string) {
        GLOBAL_DATA.error_occurred = true;
        GLOBAL_DATA.error_message = message;
    }
}