// SPDX-License-Identifier: GPL-3.0-or-later
import { DiskList, DiskListAdapter } from "../components/index.slint";
import { Button, VerticalBox, HorizontalBox } from "std-widgets.slint";

export component DiskListView {
    callback analyze-disks();
    callback update-disks <=> DiskListAdapter.update-disks;
    callback check-for-changes <=> DiskListAdapter.check-for-changes;

    update_disk_timer := Timer {
        interval: 500ms;
        triggered => {
            if (check-for-changes()) {
                update-disks();
                update-button-enabled-status();
            }
        }
    }

    function update-button-enabled-status() {
        analyzeButton.enabled = DiskListAdapter.count-selected-disks() > 0;
    }

    VerticalBox {
        padding: 20px;
        spacing: 10px;
        VerticalLayout {
            Text {
                text: @tr("Análisis de discos");
                font-weight: 800;
                font-size: 24px;
            }

            Text {
                text: @tr("Seleccione los discos que desea analizar:");
                font-size: 14px;
            }
        }

        DiskList {
            disks: DiskListAdapter.disks;
            toggle(index) => {
                DiskListAdapter.toggle-disk-checked(index);
                update-button-enabled-status();
            }
        }

        HorizontalLayout {
            alignment: center;
            analyzeButton := Button {
                primary: true;
                text: @tr("Analizar discos");
                enabled: false;
                clicked => {
                    analyze-disks();
                }
            }
        }
    }
}
