// SPDX-License-Identifier: GPL-3.0-or-later
import { DiskList, DiskListAdapter } from "../components/disk_list.slint";
import { Button, VerticalBox } from "std-widgets.slint";

export component DiskListView {
    property <int> num_selected_disks: 0;
    callback on_analyze_disk();

    VerticalBox {
        padding: 20px;
        spacing: 10px;


        VerticalLayout {
            Text {
                text: @tr("Análisis de discos");
                font-weight: 800;
                font-size: 24px;
            }
            
            Text {
                text: @tr("Seleccione los discos que desea analizar:");
                font-size: 14px;
            }
        }

        DiskList {
            disks: DiskListAdapter.disks;
    
            toggle(index) => {
                DiskListAdapter.toggle_disk_checked(index);

                if DiskListAdapter.is_checked(index) {
                    num_selected_disks += 1;
                } else {
                    num_selected_disks -= 1;
                }
            }
        }
    
        HorizontalLayout {
            alignment: center;
    
            Button {
                primary: true;
                text: @tr("Analizar discos");
                enabled: num_selected_disks > 0;

                clicked => {
                    on_analyze_disk();
                }
            }
        }
    }
}