// SPDX-License-Identifier: GPL-3.0-or-later
import { DiskList, DiskListAdapter } from "../components/disk_list.slint";
import { Button } from "std-widgets.slint";

export component DiskListView {
    VerticalLayout {
        DiskList {
            disks: DiskListAdapter.disks;
    
            toggle(index) => {
                DiskListAdapter.toggle-disk-checked(index);
            }
        }
    
        HorizontalLayout {
            alignment: center;
    
            Button {
                primary: true;
                text: @tr("Analizar discos");
            }
        }
    }
}