// SPDX-License-Identifier: GPL-3.0-or-later
import { CheckBox, ScrollView, Palette } from "std-widgets.slint";
import { Styling } from "../global.slint";

export struct DiskListItem {
    name: string,
    size: string,
    serial_number: string,
    num_partitions: int,
    num_mounted_partitions: int,
    drive_type: string,

    checked: bool,
}

export global DiskListAdapter {
    in-out property <[DiskListItem]> disks: [
        // this is only dummy data for the preview
        {
            name: "Disk 1",
            size: "1TB",
            serial_number: "123456",
            drive_type: "SSD",
        },
        {
            name: "Disk 2",
            size: "2TB",
            serial_number: "654321",
            drive_type: "HDD",
        },
    ];
    in-out property <int> num_selected_disks: count_selected_disks();

    callback toggle_disk_checked(/* index */ int);
    callback update_disks();
    pure callback count_selected_disks() -> int;
    callback update_num_selected_disks();

    // this is only a dummy implementation for the preview
    toggle_disk_checked(index) => {
        root.disks[index] = {
            name: root.disks[index].name,
            size: root.disks[index].size,
            serial_number: root.disks[index].serial_number,
            drive_type: root.disks[index].drive_type,
            num_partitions: root.disks[index].num_partitions,
            num_mounted_partitions: root.disks[index].num_mounted_partitions,
            checked: !root.disks[index].checked,
        };
    }

    pure function item(index: int) -> DiskListItem {
        root.disks[index]
    }

    pure public function is_checked(index: int) -> bool {
        root.disks[index].checked
    }

    update_num_selected_disks() => {
        root.num_selected_disks = count_selected_disks();
    }
}

export component DiskItem inherits Rectangle {
    height: icon.height + 40px;
    border-width: is_checked ? 2px : 1px;
    border-color: is_checked ? Styling.primary : Styling.border;
    border-radius: 16px;
    background: is_checked ? Styling.background-deepest : ta.has-hover ? Styling.background-weakest : Styling.background-deeper;
    drop-shadow-blur: is_checked ? 8px : 0px;
    drop-shadow-color: Styling.primary;
    drop-shadow-offset-x: 0px;

    animate border-color, background, drop-shadow-blur {
        duration: 200ms;
    }

    callback toggle;

    // Dummy implementation for the preview
    toggle() => {
        root.is_checked = !root.is_checked;
    }

    in property <string> name: "No definido";
    in property <string> size: "No definido";
    in property <string> serial_number: "No definido";
    in property <string> drive_type: "No definido";
    in property <int> num_partitions: 0;
    in property <int> num_mounted_partitions: 0;

    in-out property <bool> is_checked: false;

    property <bool> is_usb: drive_type == "USB" ? true : false;

    ta := TouchArea {
        width: 100%;
        height: 100%;

        clicked => {
            root.toggle();
        }
    }

    HorizontalLayout {
        padding: 20px;
        spacing: 16px;
        icon := Image {
            padding: 4px;
            width: 13rem;
            height: 13rem;
            source: is_usb ? @image-url("../assets/pendrive-usb.svg") : @image-url("../assets/hard-drive.svg");
        }

        VerticalLayout {
            spacing: 6px;
            alignment: start;
            HorizontalLayout {
                alignment: space-between;

                Text {
                    text: name;
                    font-size: 20px;
                    font-weight: 800;
                    padding-bottom: 4px;
                }
            }

            Text {
                text: "Tipo: " + drive_type;
                font-size: 16px;
            }

            Text {
                text: "Tamaño: " + size;
                font-size: 16px;
            }

            Text {
                text: "Número de serie: " + serial_number;
                font-size: 16px;
            }

            Text {
                text: "Particiones: " + num_partitions + " (" + num_mounted_partitions + (num_mounted_partitions == 1 ? " analizable)" : " analizables)");
                font-size: 16px;
            }
        }
    }
}

export component DiskList inherits ScrollView {
    in property <[DiskListItem]> disks;

    callback toggle(/* index */ int);

    VerticalLayout {
        spacing: 16px;

        for disk[index] in root.disks: DiskItem {
            name: disk.name;
            size: disk.size;
            serial_number: disk.serial_number;
            num_partitions: disk.num_partitions;
            num_mounted_partitions: disk.num_mounted_partitions;
            drive_type: disk.drive_type;
            is_checked: disk.checked;

            toggle => {
                root.toggle(index);
            }
        }
    }
}
