// SPDX-License-Identifier: GPL-3.0-or-later
import { SText, SIcon } from "../modules/surrealism-ui/index.slint";
import { Themes, UseSurrealismFn, ColorLevel } from "../modules/surrealism-ui/use/index.slint";
import { ROOT_GLOBAL, ROOT-GLOBAL } from "../global.slint";

struct Disk {
    name: string,
    size: string,
    serial_number: string,
    type: string,
}

// Disk Component for List Checkboxes
export component DiskComponent {
    in property <Disk> disk: {
        name: "No definido",
        size: "No definido",
        serial_number: "No definido",
        type: "No definido",
    };
    in-out property <bool> is-selected: false;
    TouchArea {
        clicked => {
            root.is-selected = !root.is-selected;
        }
        Rectangle {
            width: 100%;
            height: icon.height + 40px;
            border-width: is-selected ? 2px : 0px;
            border-color: is-selected ? UseSurrealismFn.get-color(Themes.Primary, ColorLevel.Deepest) : UseSurrealismFn.get-color(Themes.Primary, ColorLevel.Deeper);
            border-radius: 16px;
            background: is-selected ? UseSurrealismFn.get-color(ROOT-GLOBAL.theme, ColorLevel.Deepest) : UseSurrealismFn.get-color(ROOT-GLOBAL.theme, ColorLevel.Deeper);
            drop-shadow-blur: is-selected ? 8px : 0px;
            drop-shadow-color: is-selected ? UseSurrealismFn.get-color(Themes.Primary, ColorLevel.Deepest) : UseSurrealismFn.get-color(Themes.Primary, ColorLevel.Deeper);
            drop-shadow-offset-x: 0px;
            animate border-color {
                duration: 200ms;
            }
            animate background {
                duration: 200ms;
            }
            animate drop-shadow-blur {
                duration: 100ms;
            }

            HorizontalLayout {
                padding: 20px;
                spacing: 16px;
                icon := SIcon {
                    width: 18rem;
                    height: 18rem;
                    source: @image-url("../assets/hard-drive.svg");
                }

                VerticalLayout {
                    spacing: 6px;
                    alignment: start;
                    SText {
                        theme: ROOT-GLOBAL.theme;
                        text: disk.name;
                        font-size: 20px;
                        font-weight: 800;
                        padding-bottom: 4px;
                    }

                    SText {
                        theme: ROOT-GLOBAL.theme;
                        text: disk.size + " - " + disk.type;
                        font-size: 16px;
                    }

                    SText {
                        theme: ROOT-GLOBAL.theme;
                        text: "Serial: " + disk.serial_number;
                        font-size: 16px;
                    }
                }

                if is-selected: SIcon {
                    theme: ROOT-GLOBAL.theme;
                    colorize: UseSurrealismFn.get-color(Themes.Primary, ColorLevel.Weakest);
                    width: 2.5rem;
                    height: 2.5rem;
                    source: @image-url("../assets/check-circle.svg");
                }
            }
        }
    }
}

export component DisksScreenComponent {
    in property <bool> loading: false;
    VerticalLayout {
        padding: 16px;
        spacing: 12px;
        if root.loading: SText {
            text: "Loading disks...";
        }
        if !root.loading: 
            VerticalLayout {
            spacing: 12px;
            for i in [1, 2, 3]: DiskComponent {
                disk: {
                    name: "Disco " + i,
                    size: "1TB",
                    serial_number: "1234567890",
                    type: "SSD",
                };
            }
        }
    }
}
