// SPDX-License-Identifier: GPL-3.0-or-later
import { CheckBox, ScrollView, Palette } from "std-widgets.slint";
import { Styling } from "../global.slint";

export struct DiskListItem {
    name: string,
    size: string,
    serial_number: string,
    num_partitions: int,
    num_mounted_partitions: int,
    type: string,

    checked: bool,
}

export global DiskListAdapter {
    in-out property <[DiskListItem]> disks: [
        // this is only dummy data for the preview
        {
            name: "Disk 1",
            size: "1TB",
            serial_number: "123456",
            type: "SSD",
        },
        {
            name: "Disk 2",
            size: "2TB",
            serial_number: "654321",
            type: "HDD",
        },
    ];
    callback toggle_disk_checked(/* index */ int);

    // this is only a dummy implementation for the preview
    toggle_disk_checked(index) => {
        root.disks[index] = {
            name: root.disks[index].name,
            size: root.disks[index].size,
            serial_number: root.disks[index].serial_number,
            type: root.disks[index].type,
        };
    }

    function item(index: int) -> DiskListItem {
        root.disks[index]
    }
}

export component DiskItem inherits Rectangle {
    property <bool> is_checked <=> check-box.checked;

    width: 100%;
    height: icon.height + 40px;
    border-width: is_checked ? 2px : 1px;
    border-color: is_checked ? Styling.primary : Styling.border;
    border-radius: 16px;
    background: is_checked ? Styling.background-deepest : Styling.background-weakest;
    drop-shadow-blur: is_checked ? 16px : 0px;
    drop-shadow-color: Styling.primary;
    drop-shadow-offset-x: 0px;

    animate border-color {
        duration: 200ms;
    }

    animate background {
        duration: 200ms;
    }

    animate drop-shadow-blur {
        duration: 200ms;
    }

    callback toggle;

    // Dummy implementation for the preview
    toggle() => {
        root.is_checked = !root.is_checked;
    }

    in property <string> name: "No definido";
    in property <string> size: "No definido";
    in property <string> serial_number: "No definido";
    in property <string> type: "No definido";
    in property <int> num_partitions: 0;
    in property <int> num_mounted_partitions: 0;

    property <bool> is_usb: type == "USB" ? true : false;

    TouchArea {
        width: 100%;
        height: 100%;

        clicked => {
            root.toggle();
            is_checked = !is_checked;
        }
    }

    HorizontalLayout {
        padding: 20px;
        spacing: 16px;
        icon := Image {
            padding: 4px;
            width: 13rem;
            height: 13rem;
            source: is_usb ? @image-url("../assets/pendrive-usb.svg") : @image-url("../assets/hard-drive.svg");
        }

        VerticalLayout {
            spacing: 6px;
            alignment: start;
            HorizontalLayout {
                alignment: space-between;

                Text {
                    text: name;
                    font-size: 20px;
                    font-weight: 800;
                    padding-bottom: 4px;
                }

                check-box := CheckBox {
                    width: 2.5rem;
                    height: 2.5rem;
                }
            }

            Text {
                text: "Tipo: " + type;
                font-size: 16px;
            }

            Text {
                text: "Tamaño: " + size;
                font-size: 16px;
            }

            Text {
                text: "Número de serie: " + serial_number;
                font-size: 16px;
            }

            Text {
                text: "Particiones: " + num_partitions + " (" + num_mounted_partitions + (num_mounted_partitions == 1 ? " analizable)" : " analizables)");
                font-size: 16px;
            }
        }
    }
}

export component DiskList inherits ScrollView {
    in property <[DiskListItem]> disks;

    callback toggle(/* index */ int);

    VerticalLayout {
        spacing: 16px;
        for disk[index] in root.disks: DiskItem {
            name: disk.name;
            size: disk.size;
            serial_number: disk.serial_number;
            num_partitions: disk.num_partitions;
            num_mounted_partitions: disk.num_mounted_partitions;
            type: disk.type;

            toggle => {
                root.toggle(index);
            }
        }
    }
}
