// SPDX-License-Identifier: GPL-3.0-or-later
import { Button, HorizontalBox, LineEdit, VerticalBox, ScrollView } from "std-widgets.slint";
import { Styling } from "../global.slint";

export struct PathListItem {
    path: string,
    has-redundancy: bool, 
    redundancy-message: string
}

export global PathListAdapter {
    // Dummy data for the preview
    in-out property <[PathListItem]> paths: [
        {
            path: "C:/Users/Usuario/Documentos",
            has-redundancy: false,
            redundancy-message: ""
        },
        {
            path: "C:/Users/Usuario/Documentos/Proyectos",
            has-redundancy: true,
            redundancy-message: "Esta ruta es redundante con otra ruta añadida."
        },
        {
            path: "C:/Users/Usuario/Escritorio",
            has-redundancy: false,
            redundancy-message: ""
        }
    ];
    
    callback add-path(string);
    callback update-path(int, string);
    callback remove-path(int);

    pure callback redundancies-count() -> int;

    pure public function paths-count() -> int {
        return paths.length;
    }
}

export component PathItem {
    in-out property <string> path;
    in-out property <bool> is-editing: false;
    in-out property <bool> has-redundancy: false;
    in-out property <string> redundancy-message: "";
    
    callback remove();
    callback edit-confirmed(string);
    
    VerticalBox {
        spacing: 2px;
        height: has-redundancy ? 100px : 70px;
        
        HorizontalBox {
            padding: 5px;
            spacing: 10px;
            
            Rectangle {
                width: 4px;
                background: has-redundancy ? Styling.warning : transparent;
            }
            
            if (!is-editing) : Text {
                text: path;
                vertical-alignment: center;
                color: has-redundancy ? Styling.warning-dark : Styling.text;
            }
            
            if (is-editing) : LineEdit {
                text <=> path;
            }
            
            HorizontalBox {
                padding-left: 10px;
                spacing: 5px;
                alignment: end;
                
                if (!is-editing) : Button {
                    text: @tr("Editar");
                    width: 80px;
                    clicked => { is-editing = true; }
                }
                
                if (is-editing) : Button {
                    text: @tr("Guardar");
                    width: 80px;
                    clicked => { 
                        edit-confirmed(path);
                        is-editing = false;
                    }
                }
                
                Button {
                    text: @tr("Eliminar");
                    width: 80px;
                    clicked => { remove(); }
                }
            }
        }
        
        if (has-redundancy) : Rectangle {
            background: Styling.warning-bg;
            border-width: 1px;
            border-color: Styling.warning-border;
            border-radius: 4px;
            height: 30px;
            
            HorizontalBox {
                padding: 5px;
                Text {
                    text: redundancy-message;
                    color: Styling.warning-dark;
                }
            }
        }
    }
}

export component PathList {
    callback update-path(int, string);
    callback remove-path(int);

    in-out property <[PathListItem]> paths;

    ScrollView {
        min-height: 150px;
        VerticalBox {
            spacing: 5px;
            
            for path-data[index] in paths : PathItem {
                path: path-data.path;
                has-redundancy: path-data.has-redundancy;
                redundancy-message: path-data.redundancy-message;
                
                edit-confirmed(new-path-value) => {
                    update-path(index, new-path-value);
                }
                remove => {
                    remove-path(index);
                }
            }
        }
    }
}